### ISSUE TITLE
Rare crashes when no assets are returned

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/gobuilder#20]
```
panic: open /tmp/gobuild357715132/.gobuilder.yml: no such file or directory

goroutine 1 [running]:
main.orFail(0x7f0cd503fa28, 0xc208242180)
        /go/src/github.com/Luzifer/gobuilder/cmd/starter/main.go:36 +0x50
main.fetchBuildJob()
        /go/src/github.com/Luzifer/gobuilder/cmd/starter/main.go:143 +0x80a
main.main()
        /go/src/github.com/Luzifer/gobuilder/cmd/starter/main.go:85 +0x486

goroutine 17 [syscall, 11 minutes, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select, 4 minutes]:
github.com/robfig/cron.(*Cron).run(0xc208031a40)
        /go/src/github.com/robfig/cron/cron.go:152 +0xa7c
created by github.com/robfig/cron.(*Cron).Start
        /go/src/github.com/robfig/cron/cron.go:127 +0x3d

goroutine 94 [IO wait, 6 minutes]:
net.(*pollDesc).Wait(0xc208010610, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010610, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080105b0, 0xc2081ee800, 0x400, 0x400, 0x0, 0x7f0cd503dbe0, 0xc208127630)
        /usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080341e8, 0xc2081ee800, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2081c5200, 0x7f0cd503f210, 0xc2080341e8, 0x5, 0x0, 0x0)
        /usr/src/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc2082a4580, 0x17, 0x0, 0x0)
        /usr/src/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc2082a4580, 0xc2080e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/src/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f0cd5044740, 0xc2082a4580, 0xc2082bf028, 0xc2080e9000, 0x1000, 0x1000, 0xc20825c400, 0x0, 0x0)
        /usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081abb60, 0xc2080e9000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080e3620)
        /usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080e3620, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc2082befd0)
        /usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 95 [select, 6 minutes]:
net/http.(*persistConn).writeLoop(0xc2082befd0)
        /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by Luzifer** [comment]
Fixed in 05af8a2
